# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='sender',
            new_name='sender_email',
        ),
    ]
