# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180420_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='sender_email',
            new_name='Email',
        ),
    ]
