# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 00:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
