# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180420_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
