# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 10:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20180517_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(('Approved',), 'Approved'), (('Pending',), 'Pending'), ('Rejected', 'Rejected')], default=('Pending',), max_length=10)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
    ]
