# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20180608_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answered_by',
        ),
    ]
