# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('editor', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(default='media/images/', upload_to='')),
            ],
        ),
    ]
