# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180405_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/m/$D/'),
        ),
    ]
