# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to='blog/files/%Y/m/$D/'),
        ),
    ]
