# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180409_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='editor',
            new_name='user',
        ),
    ]
