# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 08:28
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=blog.models.upload_location),
        ),
    ]
