# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0004_auto_20180613_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
