# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meme', '0006_auto_20180613_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='meme_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
