# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityEvent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
