# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityEvent', '0002_event_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
